# Generated by Django 3.2 on 2021-05-14 13:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210514_1247'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='broker',
            managers=[
                ('need_to_fire', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('completed', django.db.models.manager.Manager()),
            ],
        ),
    ]
